/**
 * AstroLens — tarot dataset: the 22 Major Arcana
 * 每张牌含 正位/逆位 关键词与解读，供 Tarot Reader 工具使用。
 * 解读为娱乐与自我反思用途，不构成任何专业建议。
 */
window.TAROT = [
  { n: 0, name: 'The Fool', symbol: '🃏', keywords: 'Beginnings · Innocence · Leap of faith',
    upright: 'A fresh start, taken on trust rather than certainty. The Fool is the moment before the journey begins — open, unburdened and willing to look foolish in order to move. Say yes before you feel ready.',
    reversed: 'Recklessness, or the opposite: hesitation that has hardened into paralysis. Either you are leaping without looking, or you are refusing to start at all.' },
  { n: 1, name: 'The Magician', symbol: '🪄', keywords: 'Manifestation · Skill · Willpower',
    upright: 'You already hold every tool you need. The Magician is focused intent — the ability to take an idea and give it physical form through skill and concentration. Act; the resources are present.',
    reversed: 'Scattered energy, manipulation, or talent applied without direction. Power is there but misused or unfocused.' },
  { n: 2, name: 'The High Priestess', symbol: '🌙', keywords: 'Intuition · Mystery · Inner voice',
    upright: 'The answer is not in the data — it is in your gut. The High Priestess asks you to stop talking, stop asking and listen to what you already know. Secrets, dreams and the subconscious are active.',
    reversed: 'Ignoring intuition, or being disconnected from your inner life. Surface noise is drowning out the quiet signal.' },
  { n: 3, name: 'The Empress', symbol: '🌺', keywords: 'Abundance · Nurture · Creativity',
    upright: 'Growth, fertility and generous care. The Empress is creation that comes from nurturing rather than forcing — a project, a relationship or a body of work being fed patiently into fullness.',
    reversed: 'Neglecting yourself while caring for others, creative block, or smothering attachment. Abundance blocked by depletion.' },
  { n: 4, name: 'The Emperor', symbol: '🏛️', keywords: 'Structure · Authority · Boundaries',
    upright: 'Order, discipline and healthy authority. The Emperor builds frameworks that hold — rules, plans, boundaries. Take control of the structure rather than merely reacting to events.',
    reversed: 'Rigidity, domination or the absence of structure. Either you are being controlled, or you are refusing to take responsibility.' },
  { n: 5, name: 'The Hierophant', symbol: '📜', keywords: 'Tradition · Guidance · Belief',
    upright: 'Institutions, teachers, established wisdom and shared values. There is a proven path here and a person or tradition worth learning from. Sometimes the answer is conventional.',
    reversed: 'Rebelling against convention, or being trapped by it. Question inherited rules — but know which ones you are breaking and why.' },
  { n: 6, name: 'The Lovers', symbol: '💞', keywords: 'Union · Values · Choice',
    upright: 'Deep connection and a values-based choice. The Lovers is not only romance — it is the moment you choose what you stand for, and align your actions with it.',
    reversed: 'Misalignment, imbalance, or a choice avoided. Values and behaviour have drifted apart, or a relationship lacks honesty.' },
  { n: 7, name: 'The Chariot', symbol: '🏇', keywords: 'Willpower · Victory · Control',
    upright: 'Determined forward movement and hard-won victory. The Chariot masters opposing forces by holding the reins — conflicting feelings do not stop it, they are steered.',
    reversed: 'Loss of direction, aggression without aim, or being pulled apart by opposing impulses. Force is not the same as control.' },
  { n: 8, name: 'Strength', symbol: '🦁', keywords: 'Courage · Patience · Inner power',
    upright: 'Quiet strength and mastery through gentleness. Strength tames the lion not with a whip but with calm persistence — patience, compassion and steady nerve beat force.',
    reversed: 'Self-doubt, raw emotion running the show, or exhaustion from holding everything in. Strength depleted needs refilling.' },
  { n: 9, name: 'The Hermit', symbol: '🕯️', keywords: 'Solitude · Reflection · Inner search',
    upright: 'A deliberate retreat to find your own answers. The Hermit withdraws not from fear but for clarity — the lantern is held inward. Solitude is productive right now.',
    reversed: 'Isolation that has become avoidance, or loneliness that no longer serves. Come back down the mountain.' },
  { n: 10, name: 'Wheel of Fortune', symbol: '🎡', keywords: 'Cycles · Change · Turning point',
    upright: 'A turning point and the natural movement of cycles. Something shifts, often outside your control, and luck favours the person already in motion.',
    reversed: 'Resisting change, or a repeated cycle you have not yet broken. Bad luck is often a lesson on a loop.' },
  { n: 11, name: 'Justice', symbol: '⚖️', keywords: 'Fairness · Truth · Consequence',
    upright: 'Truth, balance and accountability. Justice asks for honesty and fact rather than wishful thinking — decisions now will be weighed, and the outcome will be fair.',
    reversed: 'Bias, dishonesty or a decision avoided. Something is out of balance and being ignored.' },
  { n: 12, name: 'The Hanged Man', symbol: '🙃', keywords: 'Pause · Surrender · New perspective',
    upright: 'A deliberate pause and a change of viewpoint. The Hanged Man gives up control temporarily and sees the situation from an entirely new angle. Waiting is the active choice here.',
    reversed: 'Stalling, martyrdom or pointless sacrifice. You are pausing for the wrong reasons, or being taken advantage of.' },
  { n: 13, name: 'Death', symbol: '🦋', keywords: 'Ending · Transformation · Release',
    upright: 'A definitive ending that makes room for something new. Death is rarely literal — it is the closing of a chapter that has already finished, and the transformation that follows release.',
    reversed: 'Holding on to what is already over, or resisting an inevitable transition. Grief in progress.' },
  { n: 14, name: 'Temperance', symbol: '🏺', keywords: 'Balance · Patience · Moderation',
    upright: 'Patient blending of opposites. Temperance is the middle path — measured, unhurried, and confident that slow consistent effort produces the right result. Healing is underway.',
    reversed: 'Excess, imbalance or impatience. Something is being done in the wrong proportion, or too fast.' },
  { n: 15, name: 'The Devil', symbol: '⛓️', keywords: 'Attachment · Temptation · Shadow',
    upright: 'Bondage that is chosen. The Devil points to a habit, desire or dependency you are not free from — and the chains are looser than they look. Name the thing and its power drops.',
    reversed: 'Breaking free. Awareness has arrived and the hold is loosening, though it may take deliberate effort to fully release.' },
  { n: 16, name: 'The Tower', symbol: '🗼', keywords: 'Upheaval · Revelation · Collapse',
    upright: 'Sudden upheaval that destroys what was not built on solid ground. The Tower is brutal and clarifying — after it, only what is true remains standing.',
    reversed: 'Avoiding a necessary collapse, or a slow-motion crisis. The longer the reckoning is delayed, the bigger it gets.' },
  { n: 17, name: 'The Star', symbol: '⭐', keywords: 'Hope · Renewal · Guidance',
    upright: 'Calm hope after difficulty. The Star is healing and renewed faith — quiet inspiration, guidance from within, and the sense that things are returning to flow.',
    reversed: 'Doubt, discouragement or losing faith in a vision. The light is still there; you have simply stopped looking up.' },
  { n: 18, name: 'The Moon', symbol: '🌕', keywords: 'Illusion · Fear · Subconscious',
    upright: 'Uncertainty and illusion. The Moon reveals that things are not what they appear — anxiety, dreams and intuition are all active. Do not commit to decisions made in the dark.',
    reversed: 'Confusion clearing, or truth surfacing. Fear is losing its grip and the real picture is emerging.' },
  { n: 19, name: 'The Sun', symbol: '☀️', keywords: 'Joy · Success · Vitality',
    upright: 'Clarity, joy and success. The Sun is one of the most positive cards in the deck — genuine happiness, achievement and the freedom to be fully yourself. Good news is on the way.',
    reversed: 'Temporary dimming of joy, or success that is not fully satisfying. The light is present but partly blocked.' },
  { n: 20, name: 'Judgement', symbol: '📣', keywords: 'Awakening · Reckoning · Renewal',
    upright: 'A wake-up call and a genuine rebirth. Judgement is honest self-assessment — you see your history clearly, forgive what needs forgiving, and rise into a new version of yourself.',
    reversed: 'Avoiding accountability, or being paralysed by past mistakes. Self-forgiveness is the missing step.' },
  { n: 21, name: 'The World', symbol: '🌍', keywords: 'Completion · Wholeness · Fulfilment',
    upright: 'Completion and integration. The World marks the end of a long cycle — the goal reached, the lesson learned, the whole made from the parts. A chapter closes with real satisfaction.',
    reversed: 'A cycle almost, but not quite, finished. Something is left undone before the next chapter can begin.' }
];
